#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Building code'
dotnet build CsvImportDemo.sln

echo 'Formatting code'
dotnet format CsvImportDemo.sln --verify-no-changes

echo 'Run Test'
dotnet test CsvImportDemo.sln


